trigger: none

pool:
  vmImage: ubuntu-latest
#some comment
jobs:
- job: BicepDeployment
  steps:
  
  - task: AzureCLI@2
    inputs:
      azureSubscription:  #$(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
       az deployment sub create \
       -f main.bicep \
       -l $(location) \
       -p rgName=$(rgname) appName=$(appName)
